### PR TITLE
labwc icons: Add updated icons

### PR DESCRIPTION
**Pull request by rcalixte**
Ref: #7, labwc/labwc#1462

cc @Consolatis @johanmalm (The PR is open for edits as needed. I'll try to remember not to rebase.)

### CODE REVIEW

**Review by 01micko — DISMISSED** [review]
Symbolic icons as far as I know only use one color so I don't think black and white fits the bill.

```svg
<?xml version="1.0" encoding="UTF-8"?>
<!--labwc logo #2 (C) Johan Malm LICENSE: CC BY-SA 4.0-->
<svg xmlns="http://www.w3.org/2000/svg" width="256px" height="256px"
     viewbox="0 0 256 256"
     stroke-linecap="round" stroke-linejoin="round" stroke-width="12">
  <path fill="none" stroke="#000000" d="m 26 68 91 55 v 108 l -76 -61 z" />
  <path fill="#000000" stroke="#000000" d="m 229 68 -91 55 v 108 l 76 -61 z" />
</svg>

```

**Comment by rcalixte** [comment]
> Symbolic icons as far as I know only use one color so I don't think black and white fits the bill.

Just when I thought I'd finally gotten this right... Would be better to use `#ffffff` instead though? That seems to work better in my testing.

**Comment by 01micko** [comment]
Not sure. Trying to research this through freedesktop but all there is is broken links! I might retract that 'request changes' due to lack of information. And I was wrong, not all symbolic icons are single color. Found some with warning signs overlaid and also some battery icons have color.

I would be inclined to add the outline to the white in black. But that's just me.

**Comment by rcalixte** [comment]
For reference:

With `#000000`:



With `#ffffff`:



I'm not sure why it differs to be honest here either. 😅



> I would be inclined to add the outline to the white in black. But that's just me.

I'll leave this up to the team. I'll gladly do whatever the wisdom of the crowd desires.

**Comment by 01micko** [comment]
Since my initial criticism is unfounded I can merge this. The icons are the same as in the main repo so all good.

**Pull request merged**
