### PR TITLE
adwaita-papyrus-dark: new theme

### PR DESCRIPTION
**Pull request by jp7677**
Based on the work of others, this is my interpretation of a a Labwc SSD appearance. As the readme states, I tried to be as close as possible to GTK3/4 CSD applications with the Papirus icon theme to have a consistent SSD/CSD appearance. I'm happy with how it looks, so I thought I share.

MPV screenshot with SSD:

Screenshot

To compare, this is how Gnome Calculator with CSD appears:

Screenshot

PS: I recommend to squash. Also I hope that the screenshot in the readme works like in the fork repo (https://github.com/jp7677/labwc-artwork/tree/adwaita-papyrus-dark/themes/Adwaita-Papirus-dark).

### CODE REVIEW

**Comment by 01micko** [comment]
Nice! I'm going to try now.

**Comment by 01micko** [comment]
Looks good.

I used galculator because it has an `xpm` icon to get a look at the menu icon in play.

galculator


Seems to be inconsistencies with menu and desk. Menu isn't likely to matter as many users would use window icons .

@johanmalm ?

**Comment by jp7677** [comment]
If you really want to use all icons, a titlebar configuration/order like this looks probably better:

```xml
<titlebar layout="desk:menu,iconify,shade,max,close" showTitle="yes" />
``` 

I've indeed omitted `icon` in my configuration, since GTK/Adwaita also don't use a window icon.

**Comment by 01micko** [comment]
I get your point. I can see the consistency with the CSD.

LGTM

**Comment by 01micko** [comment]
Screenshot survived the merge :)

**Pull request merged**
